syntax = "proto3";

package auth;

service AuthService {
  rpc Register (RegisterRequest) returns (RegisterResponse);
  rpc Login (LoginRequest) returns (LoginResponse);
  rpc VerifyOTP (VerifyOTPRequest) returns (VerifyOTPResponse);
}

message RegisterRequest {
  string name = 1;
  string password = 2;
  string email = 3;
}

message RegisterResponse {
  bool success = 1;
  string message = 2;
}

message LoginRequest {
  string name = 1;
  string password = 2;
}

message LoginResponse {
  bool success = 1;
  string message = 2;
}

message VerifyOTPRequest {
  string name = 1;
  string otp = 2;
}

message VerifyOTPResponse {
  bool success = 1;
  string token = 2;
  string message = 3;
}