# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: node.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'node.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nnode.proto\x12\x04node\"1\n\x0cStoreRequest\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\x0c\"1\n\rStoreResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"#\n\x0fRetrieveRequest\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\"E\n\x10RetrieveResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\x0c\x12\x0f\n\x07message\x18\x03 \x01(\t\"!\n\rRemoveRequest\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\"2\n\x0eRemoveResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"\x12\n\x10NodeSpaceRequest\"0\n\x11NodeSpaceResponse\x12\r\n\x05total\x18\x01 \x01(\x03\x12\x0c\n\x04used\x18\x02 \x01(\x03\x32\xfc\x01\n\x0bNodeService\x12\x34\n\tStoreFile\x12\x12.node.StoreRequest\x1a\x13.node.StoreResponse\x12=\n\x0cRetrieveFile\x12\x15.node.RetrieveRequest\x1a\x16.node.RetrieveResponse\x12\x37\n\nRemoveFile\x12\x13.node.RemoveRequest\x1a\x14.node.RemoveResponse\x12?\n\x0cGetNodeSpace\x12\x16.node.NodeSpaceRequest\x1a\x17.node.NodeSpaceResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'node_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_STOREREQUEST']._serialized_start=20
  _globals['_STOREREQUEST']._serialized_end=69
  _globals['_STORERESPONSE']._serialized_start=71
  _globals['_STORERESPONSE']._serialized_end=120
  _globals['_RETRIEVEREQUEST']._serialized_start=122
  _globals['_RETRIEVEREQUEST']._serialized_end=157
  _globals['_RETRIEVERESPONSE']._serialized_start=159
  _globals['_RETRIEVERESPONSE']._serialized_end=228
  _globals['_REMOVEREQUEST']._serialized_start=230
  _globals['_REMOVEREQUEST']._serialized_end=263
  _globals['_REMOVERESPONSE']._serialized_start=265
  _globals['_REMOVERESPONSE']._serialized_end=315
  _globals['_NODESPACEREQUEST']._serialized_start=317
  _globals['_NODESPACEREQUEST']._serialized_end=335
  _globals['_NODESPACERESPONSE']._serialized_start=337
  _globals['_NODESPACERESPONSE']._serialized_end=385
  _globals['_NODESERVICE']._serialized_start=388
  _globals['_NODESERVICE']._serialized_end=640
# @@protoc_insertion_point(module_scope)
