# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: storage.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'storage.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rstorage.proto\x12\x07storage\"A\n\rUploadRequest\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\x0c\x12\r\n\x05token\x18\x03 \x01(\t\"2\n\x0eUploadResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"2\n\x0f\x44ownloadRequest\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\x12\r\n\x05token\x18\x02 \x01(\t\"E\n\x10\x44ownloadResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\x0c\x12\x0f\n\x07message\x18\x03 \x01(\t\"0\n\rDeleteRequest\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\x12\r\n\x05token\x18\x02 \x01(\t\"2\n\x0e\x44\x65leteResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"\x1c\n\x0bListRequest\x12\r\n\x05token\x18\x01 \x01(\t\"!\n\x0cListResponse\x12\x11\n\tfilenames\x18\x01 \x03(\t\"\x1d\n\x0cSpaceRequest\x12\r\n\x05token\x18\x01 \x01(\t\",\n\rSpaceResponse\x12\r\n\x05total\x18\x01 \x01(\x03\x12\x0c\n\x04used\x18\x02 \x01(\x03\x32\xc8\x02\n\x0eStorageService\x12=\n\nUploadFile\x12\x16.storage.UploadRequest\x1a\x17.storage.UploadResponse\x12\x43\n\x0c\x44ownloadFile\x12\x18.storage.DownloadRequest\x1a\x19.storage.DownloadResponse\x12=\n\nDeleteFile\x12\x16.storage.DeleteRequest\x1a\x17.storage.DeleteResponse\x12\x38\n\tListFiles\x12\x14.storage.ListRequest\x1a\x15.storage.ListResponse\x12\x39\n\x08GetSpace\x12\x15.storage.SpaceRequest\x1a\x16.storage.SpaceResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'storage_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_UPLOADREQUEST']._serialized_start=26
  _globals['_UPLOADREQUEST']._serialized_end=91
  _globals['_UPLOADRESPONSE']._serialized_start=93
  _globals['_UPLOADRESPONSE']._serialized_end=143
  _globals['_DOWNLOADREQUEST']._serialized_start=145
  _globals['_DOWNLOADREQUEST']._serialized_end=195
  _globals['_DOWNLOADRESPONSE']._serialized_start=197
  _globals['_DOWNLOADRESPONSE']._serialized_end=266
  _globals['_DELETEREQUEST']._serialized_start=268
  _globals['_DELETEREQUEST']._serialized_end=316
  _globals['_DELETERESPONSE']._serialized_start=318
  _globals['_DELETERESPONSE']._serialized_end=368
  _globals['_LISTREQUEST']._serialized_start=370
  _globals['_LISTREQUEST']._serialized_end=398
  _globals['_LISTRESPONSE']._serialized_start=400
  _globals['_LISTRESPONSE']._serialized_end=433
  _globals['_SPACEREQUEST']._serialized_start=435
  _globals['_SPACEREQUEST']._serialized_end=464
  _globals['_SPACERESPONSE']._serialized_start=466
  _globals['_SPACERESPONSE']._serialized_end=510
  _globals['_STORAGESERVICE']._serialized_start=513
  _globals['_STORAGESERVICE']._serialized_end=841
# @@protoc_insertion_point(module_scope)
